# Generated by Django 4.1 on 2022-11-21 03:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("second_name", models.CharField(max_length=100)),
                ("patronymic", models.CharField(max_length=100)),
                ("age", models.IntegerField(default=18)),
                (
                    "gender",
                    models.CharField(
                        choices=[("male", "мужчина"), ("female", "женшина")],
                        max_length=100,
                    ),
                ),
                ("was_born", models.DateField(default="2004-01-01")),
                ("passport_left", models.FileField(upload_to="document")),
                ("passport_right", models.FileField(upload_to="document")),
                ("recipient_amonatbonck", models.FileField(upload_to="amonatbonck")),
                ("phone", models.CharField(max_length=200)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "status_document",
                    models.CharField(
                        choices=[
                            ("Готово", "done"),
                            ("Астывна", "active"),
                            ("Отменён", "block"),
                        ],
                        default="Астывна",
                        max_length=100,
                    ),
                ),
                ("message", models.TextField(blank=True, default="Test Message")),
                ("created_at", models.DateTimeField(auto_now=True, null=True)),
                ("update_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("email", models.EmailField(max_length=254)),
                ("editable", models.BooleanField(default=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
